#-*- coding: UTF-8 -*-
doctorinfo_nosum = [
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211106",
                "doctor_name":"陈存国",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"M",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"35",
                "sum_dqkyysl":"15",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长呼吸道疾病、老年病及同时患有多种慢性疾病的综合诊治，尤其对慢性咳嗽、肺结节、慢性支气管炎、肺气肿、哮喘、肺炎、无创呼吸机的应用、老年人综合病的治疗有丰富经验。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211107",
                "doctor_name":"李宗平",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"F",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"34",
                "sum_dqkyysl":"47",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长呼吸道疾病、老年病及同时患有多种慢性疾病的综合诊治，尤其对慢性咳嗽、肺结节、慢性支气管炎、肺气肿、哮喘、肺炎、无创呼吸机的应用、老年人综合病的诊治方面有丰富的临床经验。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211164",
                "doctor_name":"姚桂飞",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"F",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"97",
                "sum_dqkyysl":"50",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长肺癌的精准和综合治疗，慢性阻塞性肺疾病、支气管哮喘、胸腔积液、肺部感染性疾病、间质性肺炎、睡眠呼吸暂停综合症等常见病及疑难病的诊断和治疗以及支气管镜、内科胸腔镜的操作。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211182",
                "doctor_name":"林云",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"M",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"25",
                "sum_dqkyysl":"215",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长呼吸科常见病诊治、呼吸道感染性疾病、胸膜腔疾病和支气管镜的检查及介入治疗，常见病诊治、呼吸道感染性疾病。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211283",
                "doctor_name":"单仁飞",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"M",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"6",
                "sum_dqkyysl":"14",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长各种内科急危重病的诊断和抢救治疗、严重多发伤的综合性治疗、各种中毒疾病的抢救治疗、各种急诊人工气道的建立、呼吸窘迫综合症、外科性疾病围手术期的脏器功能支持、多脏器功能不全综合征的抢救治疗，各种急性感染性疾病的治疗等情况。每年抢救各类急危重病例在1000俐以上。近3年带领急诊科团队开展ECMO治疗技术抢救常规治疗无效的心肺功能衰竭，每年例数在20人以上。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211353",
                "doctor_name":"齐激扬",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"M",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"23",
                "sum_dqkyysl":"77",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长呼吸系统疾病的诊治，及老年医学、危重病、疑难病诊治。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211400",
                "doctor_name":"徐有祖",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"M",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"65",
                "sum_dqkyysl":"75",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长肺癌的诊断和综合治疗、支气管哮喘、慢性阻塞性肺病、阻塞性睡眠呼吸暂停综合症、肺部感染性疾病的诊治，以及呼吸内科的危重病、疑难病诊断和治疗。支气管镜、超声支气管镜、内科电子胸腔镜等介入诊疗技术。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211516",
                "doctor_name":"王慧红",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"F",
                "doctor_age":"",
                "doctor_title":"副主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"16",
                "sum_dqkyysl":"45",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长呼吸内科常见疾病的诊治，尤其对慢阻肺、支气管哮喘、咳嗽、肺结节、肺部感染等疾病的诊治有丰富经验。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211531",
                "doctor_name":"周炜",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"M",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"6",
                "sum_dqkyysl":"64",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长呼吸科各种常见病、内科多系统累及慢性病、全科未分化疾病的诊治，特别是慢阻肺等慢性气道炎症性疾病、慢性咳嗽和呼吸道感染性疾病的诊治。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211555",
                "doctor_name":"何苏苏",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"F",
                "doctor_age":"",
                "doctor_title":"副主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"27",
                "sum_dqkyysl":"63",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长肺癌、慢性阻塞性肺病、哮喘、弥漫性肺病、肺部感染等。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211638",
                "doctor_name":"陈美芳",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"F",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"75",
                "sum_dqkyysl":"40",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长肺癌、间质性肺病的诊断和治疗，以及支气管哮喘、慢性阻塞性肺疾病、阻塞性睡眠呼吸暂停综合征、肺部感染性疾病等常见疾病的诊治，擅长支气管镜下各种介入治疗，同时在呼吸内科危重症和疑难病的诊治方面具有丰富经验。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211642",
                "doctor_name":"林玲",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"F",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"50",
                "sum_dqkyysl":"10",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长肺癌，肺小结节，慢性咳嗽，哮喘，慢性支气管炎，肺部感染性疾病，间质性肺病，过敏性疾病，脱敏免疫治疗。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211816",
                "doctor_name":"周灵芳",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"F",
                "doctor_age":"",
                "doctor_title":"副主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"4",
                "sum_dqkyysl":"46",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长呼吸道疾病、老年病及同时患有多种慢性疾病的综合诊治，尤其对慢性咳嗽、肺结节、慢性支气管炎、肺气肿、哮喘、肺炎、无创呼吸机的应用、老年人综合病的治疗有丰富经验。"
            },
            {
                "hospital_id":"47258021",
                "hospital_name":"台州医院",
                "department_type":"3",
                "department_id":"310",
                "department_name":"呼吸与危重症医学科专",
                "doctor_id":"472580211908",
                "doctor_name":"吴小脉",
                "doctor_photo":"https://www.yunjk.net.cn/AttachmentPath/Docs/NoPic.jpg",
                "doctor_sex":"M",
                "doctor_age":"",
                "doctor_title":"主任医师",
                "doctor_general":"N",
                "doctor_yyysl":"9",
                "sum_dqkyysl":"31",
                "doctor_special":"N",
                "doctor_be_good_at":"擅长重症肺炎、严重气道疾病等呼吸危重症救治；间质性肺炎、胶原血管病肺受累等弥漫性肺疾病诊治以及支气管镜、超声支气管镜、内科电子胸腔镜等介入诊疗技术。"
            }
        ]
def getRepeatDoctor():
    repeat_doctorinfo = []  # 重复的医生信息
    seen = set()
    # new_l = []
    for docinfo in doctorinfo_nosum:
        t = tuple(docinfo.items())
        # print(t)
        if t not in seen:
            seen.add(t)
            # new_l.append(docinfo)
        else:
            print('医生列表数据重复：'
                  '-->' + docinfo['department_id'] + docinfo['department_name'] +
                  '-->' + docinfo['doctor_id'] + docinfo['doctor_name'])
            repeat_doctorinfo.append(docinfo)

    # print(new_l)
    if repeat_doctorinfo == []:
        print('没有重复医生数据......')
    # print(json.dumps(repeat_doctorinfo))
    repeat_doctorinfo = repeat_doctorinfo
    return repeat_doctorinfo

getRepeatDoctor()

